### ISSUE TITLE
Ejercicio 2

### ISSUE THREAD

**Issue by ivanfretes** [crisort77/repositorio01#2]
- Como funciona en Hackerank, detallar procesos para hacer funcionar el programa

**Comment by crisort77** [comment]
El hackerank pase en un formato .txt.
Para que funcione se copia y pega en la página
https://www.hackerrank.com/challenges/2d-array/problem reemplazando el
codigo de la captura de abajo.
Posterior al copiado se hace click a "Submit Code" y luego "Run code". La
misma lanza el resultado al corregir el ejercicio.
El ejercicio consta de completar el código faltante el cual es lanzado de
forma aleatoria para que la persona pueda aplicar sus conocimientos.

Saludos
[image: image.png]

**Comment by ivanfretes** [comment]
Lo que no encuentro, pese a que funciona. Es la función **hourglassSum**
Lo ideal seria que puedas seguir las instrucciones en el repositorio, y seguir todos los pasos. con sus respectivas explicaciones

![Captura de pantalla de 2020-07-14 11-34-39](https://user-images.githubusercontent.com/751387/87445439-0ec1cd80-c5c6-11ea-9f2c-79e292020589.png)

**Comment by crisort77** [comment]
Me acuerdo que había borrado esa función por que según entendí no era
necesario que este ahí.
Y estoy por implementar todos los métodos faltantes para luego alzar en
repositorio con la explicaciones.

**Comment by ivanfretes** [comment]
En el enunciado te pide la función, es parte del Ejercicio. (De cierta forma es parte de la **Abstracción**)

**Comment by crisort77** [comment]
Voy a verificar después de terminar el CRUD
